app/urls.py
from django.urls import path


from .views import home, create_blog, login_view, logout_view, signup_view, detail_blog, edit_blog

from .views_cbv import CreateBlogView, HomePageView
app_name = 'app'

urlpatterns = [
    # path('', home, name='home'),
    # path('create/', create_blog, name='create'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
    path('blog/<int:id>', detail_blog, name='detail'),
    path('blog/<slug:slug>', edit_blog, name='edit'),
]

urlpatterns_cbv = [
    path('', HomePageView.as_view(), name='home'),
    path('create', CreateBlogView.as_view(), name='create'),
]
urlpatterns += urlpatterns_cbv

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from account.managers import UserManager


class CustomUser(AbstractUser):
    phone = models.CharField(max_length=13, unique=True)
    image = models.ImageField(upload_to='profile_pics/', null=True, blank=True)
    bio = models.TextField(null=True, blank=True)

    USERNAME_FIELD = 'username'
    objects = UserManager()

app/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.text import slugify

from app.managers import BlogManager

User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Blog(models.Model):
    title = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='blogs/', null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)

    objects = BlogManager()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Blog, self).save(*args, **kwargs)


class Comments(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    reply = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

account/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("username",)

app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from .models import Blog, Comments

User = get_user_model()


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100, widget=forms.PasswordInput)


class SignupForm(UserCreationForm):
    username = forms.CharField(max_length=100, error_messages={'exists': 'Username is already exists.'})
    # phone = forms.CharField(max_length=13)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            # 'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
        }


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'description', 'image', 'category']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['text']

account/views.py
from django.shortcuts import render

# Create your views here.

app/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.contrib import messages

from django.urls import reverse

from app.models import Blog
from .forms import BlogForm, LoginForm, SignupForm, CommentForm


def home(request):
    blogs = Blog.objects.all()

    return render(request, 'home.html', {'blogs': blogs})


def login_view(request):
    form = LoginForm()
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(reverse('app:home'))

    return render(request, 'login.html', {'form': form})


def signup_view(request):
    form = SignupForm()
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('app:login'))
        # print(form.errors)
    return render(request, 'sign_up.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect(reverse('app:login'))


@login_required(login_url='/login/')
def create_blog(request):
    form = BlogForm()
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES)
        if not request.user.is_authenticated:
            messages.warning(request, 'Avval login qiling')
            return redirect(reverse('app:create'))
        if form.is_valid():
            blog = form.save(commit=False)
            blog.author = request.user
            blog.save()
        return redirect(reverse('app:home'))

    context = {'form': form}
    return render(request, 'create_blog.html', context)


def detail_blog(request, id):
    blog = get_object_or_404(Blog, id=id)
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.blog = blog
            comment.author = request.user
            comment.save()
            return redirect('app:detail', blog.id)
    context = {
        "blog": blog,
        "form": form,
    }
    return render(request, 'detail_blog.html', context)


@login_required(login_url='/login/')
def edit_blog(request, slug):
    blog = get_object_or_404(Blog, slug=slug)
    if request.user != blog.author:
        messages.warning(request, 'Bu blog sizga tegishli emas!')
        return redirect('app:login')
    form = BlogForm(instance=blog)
    if request.method == "POST":
        form = BlogForm(request.POST, request.FILES, instance=blog)
        if not request.user.is_authenticated:
            messages.warning(request, 'Avval login qiling')
            return redirect(reverse('app:create'))
        if form.is_valid():
            blog = form.save()
            return redirect('app:detail', blog.id)
    context = {
        'form': form,
        'blog': blog,
    }
    return render(request, 'edit_blog.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>
<body>
<header>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <a href="{% url 'app:home' %}">Home</a> |
    <a href="{% url 'app:create' %}">Create Blog</a> |
    {% if user.is_authenticated %}
        <a href="#">{{ user.username }}</a> |
        <a href="{% url 'app:logout' %}">Logout</a> |
    {% else %}
        <a href="{% url 'app:login' %}">Login</a> |
        <a href="{% url 'app:signup' %}">Sign Up</a> |
    {% endif %}
    <br>
    <br>
</header>

<div>
    {% block content %}

    {% endblock %}
</div>

<footer>

</footer>

</body>
</html>

templates/create_blog.html
{% extends 'base.html' %}


{% block title %} Create Blog {% endblock %}

{% block content %}

    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Save">
    </form>

{% endblock %}

templates/detail_blog.html
{% extends 'base.html' %}


{% block title %} {{ blog.title }} {% endblock %}

{% block content %}
    
        <p>{{ blog.title }}</p>
        <p>{{ blog.description }}</p>
        {% if blog.image %}
            <img src="{{ blog.image.url }}">
        {% endif %}
        <p>{{ blog.created_at }}</p>
        <p>{{ blog.updated_at }}</p>
        <p>{{ blog.author }}</p>
        <p>{{ blog.category }}</p>
<hr>
    {% if request.user == blog.author %}
    <p><a href="{% url 'app:edit' blog.slug %}">Edit</a></p>
    {% endif %}

    <hr>
    <div class="row">
    <div class="col-6">
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit">Save</button>
        </form>
    </div>
    <div class="col-6">
        {% for comment in blog.comments_set.all %}
            <p>{{ comment.text }}</p>
            <p>{{ comment.author }}</p>
        {% endfor %}
    </div>

    </div>

{% endblock %}

templates/edit_blog.html
{% extends 'base.html' %}


{% block title %} Update Blog {% endblock %}

{% block content %}

    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Update Blog">
    </form>

{% endblock %}

templates/home.html
{% extends 'base.html' %}


{% block title %} Home {% endblock %}

{% block content %}
    <h1>{{ text }}</h1>
    {% for blog in blogs %}
        <p><a href="{% url 'app:detail' blog.id %}">{{ blog.title }}</a></p>
    {% endfor %}
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Login</button>
    </form>

{% endblock %}

templates/sign_up.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Sign Up {% endblock %}


{% block content %}
    <h3>Sign Up page</h3>
   <form method="post">
   {% csrf_token %}
       <div class="mb-3">
    <label class="form-label">Username</label>
        {{ form.username }}
           {{ form.errors.username }}
  </div>
  <div class="mb-3">
    <label class="form-label">Email address</label>
    {{ form.email }}
       {{ form.errors.email }}
  </div>
  <div class="mb-3">
    <label class="form-label">Password</label>
    {{ form.password1 }}
  </div>
       <div class="mb-3">
    <label class="form-label">{{ form.password2.label }}</label>
    {{ form.password2 }}
  </div>
  <button type="submit" class="btn btn-primary">Sign Up</button>
</form>

{% endblock %}